### ISSUE TITLE
FoF user bio not able to be translated

### ISSUE THREAD

**Issue by OddDev** [FriendsOfFlarum/linguist#14]
When having FoF/user-bio installed, it's not in the list to be translated. 
![image](https://user-images.githubusercontent.com/11198480/65852599-e4fd2a00-e356-11e9-83bd-0af32439b553.png)

**Comment by clarkwinkelmann** [comment]
FoF bio is using a non standard translation namespace, so this is probably
the reason it doesn't show up (expected: fof-user-bio, actual: fof-userbio)

You can still look for the strings by typing "fof-userbio" in the search
field.

We could improve the extension so it lets you know that no translations
were found in the expected namespace.

**Comment by OddDev** [comment]
@clarkwinkelmann you are absolutely right :)

**Comment by clarkwinkelmann** [comment]
Extensions with non-standard namespace now show as greyed out in the extension filter with a message if clicked on them.

I will consider this as solved.
