### ISSUE TITLE
[Feature request] Download translation file

### ISSUE THREAD

**Issue by maicol07** [FriendsOfFlarum/linguist#15]
Hi,
I would like to download the translated yml file from Linguist. Would this be possible?
Thanks

**Comment by clarkwinkelmann** [comment]
This is a planned feature.

I actually started working on it last week during my live stream, but quickly realized it's a bit more complex than expected. So it's still a work in progress.

For now the only option is to export strings from the database, but they won't be in a format that can be easily dropped into an yml file.

**Comment by clarkwinkelmann** [comment]
Implemented in 0.5.1
