### ISSUE TITLE
Extiverse bazaar cannot be translated

### ISSUE THREAD

**Issue by maicol07** [FriendsOfFlarum/linguist#16]
Bazaar doesn't show up in the translatable extensions list

**Comment by maicol07** [comment]
Update: searching Bazaar in strings works but it doesn't show up in extensions dropdown

**Comment by clarkwinkelmann** [comment]
Same thing as #14 . This is considered a feature. I have just added an explanation message in the new release so people can know why an extension isn't offered in that filter.
