### ISSUE TITLE
Refactor to work with locales cache in beta 9

### ISSUE THREAD

**Issue by clarkwinkelmann** [FriendsOfFlarum/linguist#8]
The current implementation won't work anymore once https://github.com/flarum/core/commit/0d16fac001bb735ee66e82871183516aeac269b7 will be released, probably in beta 9.

The main issue with this extension is that we need to be able to get the default translations without any override to display them in the admin panel. Currently there's a global lock file that allows to export the translations without having linguist injecting anything. This won't work anymore once caching is enabled.

Clearing the cache before and after loading default translations is an option, but then we should cache those default translations so visiting Linguist tab doesn't clear the locales cache even if you don't change anything.

Then of course we need to call `app('flarum.locales')->clearCache();` every time a translations is edited. That's the easy part.

**Comment by luceos** [comment]
Shouldn't you be able to inject a tmp lang file into the locales loader which you dynamically seed whenever the linguist settings are modified?

**Comment by clarkwinkelmann** [comment]
@luceos that's exactly what already happens. Right now it's always pulling from database so that's maybe not the most efficient option. Once locales caching comes it will be able to use that.

The problem is getting a copy of the untouched locales without clearning the cache.

In beta 7 I could replay the events and force extensions to register their locales on a custom locales manager where Linguist could easily not add itself. But now there are no events to replay anymore.

All loaded data is directly added to the global locales manager. Right now there's no cache so I can globally disable my loader and ask for default translations directly.

In order to get uncached but fresh default translations with cache enabled, I'd need to somehow clone the manager into a second one where I disable caching, then export with Linguist injection disabled. It's not easy though, because symfony made sure everything is private and you can only add, never remove :crying_cat_face: 

The easiest solution will probably be to just listen for extensions being enabled or disabled, take the opportunity while cache is already cleared to extract default translations, then cache those so we can display them in the admin panel later whenever we want without having to use special tricks. Just after having grabbed those default translations we can clear the cache again and let it be refilled with the overriden translations.

**Comment by clarkwinkelmann** [comment]
I don't think this needs too much further discussion, I've kind of already figured it out.

The issue just needs to remain open until the translations cache is released in Flarum. It's not possible to already implement the changes, because we need the locales cache clearing command available, and it's not in beta 8.

**Comment by irkmix** [comment]
It will wait, because without this extension, my site has lost MY translation
